// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOS_Buscas_V2.Data;

#nullable disable

namespace SOS_Buscas_V2.Migrations
{
    [DbContext(typeof(BancoContext))]
    partial class BancoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SOS_Buscas_V2.Models.AvistamentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DesaparecidoId")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoDesaparecido")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DiaHoraAvistamento")
                        .HasColumnType("DateTime");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.HasIndex("DesaparecidoId");

                    b.HasIndex("UserEmail");

                    b.ToTable("Avistamentos");
                });

            modelBuilder.Entity("SOS_Buscas_V2.Models.DesaparecidoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Altura")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("CaminhoImagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorPele")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("DataHoraDesaparecimento")
                        .HasColumnType("DateTime");

                    b.Property<string>("Doencas")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("EstiloCorCabelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mediacacoes")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Tatoagem")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Transtornos")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vestimenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmailUsuario");

                    b.ToTable("Desaparecidos");
                });

            modelBuilder.Entity("SOS_Buscas_V2.Models.EnderecoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("DesaparecidoId")
                        .HasColumnType("int");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.HasIndex("DesaparecidoId");

                    b.HasIndex("UserEmail");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("SOS_Buscas_V2.Models.LocalAvistamentoModel", b =>
                {
                    b.Property<int>("AvistamentoID")
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PontoReferencia")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rua")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasIndex("AvistamentoID");

                    b.ToTable("localAvistamentoModels");
                });

            modelBuilder.Entity("SOS_Buscas_V2.Models.UsuarioModel", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("DateTime");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("Email");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SOS_Buscas_V2.Models.AvistamentoModel", b =>
                {
                    b.HasOne("SOS_Buscas_V2.Models.DesaparecidoModel", "IdDesaparecido")
                        .WithMany()
                        .HasForeignKey("DesaparecidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOS_Buscas_V2.Models.UsuarioModel", "Email")
                        .WithMany()
                        .HasForeignKey("UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("IdDesaparecido");
                });

            modelBuilder.Entity("SOS_Buscas_V2.Models.DesaparecidoModel", b =>
                {
                    b.HasOne("SOS_Buscas_V2.Models.UsuarioModel", "Email")
                        .WithMany()
                        .HasForeignKey("EmailUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("SOS_Buscas_V2.Models.EnderecoModel", b =>
                {
                    b.HasOne("SOS_Buscas_V2.Models.DesaparecidoModel", "IdDesaparecido")
                        .WithMany()
                        .HasForeignKey("DesaparecidoId");

                    b.HasOne("SOS_Buscas_V2.Models.UsuarioModel", "Email")
                        .WithMany()
                        .HasForeignKey("UserEmail");

                    b.Navigation("Email");

                    b.Navigation("IdDesaparecido");
                });

            modelBuilder.Entity("SOS_Buscas_V2.Models.LocalAvistamentoModel", b =>
                {
                    b.HasOne("SOS_Buscas_V2.Models.AvistamentoModel", "IdAvistamento")
                        .WithMany()
                        .HasForeignKey("AvistamentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdAvistamento");
                });
#pragma warning restore 612, 618
        }
    }
}
