// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOS_Buscas.Data;

#nullable disable

namespace SOS_Buscas.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20230529180936_banco")]
    partial class banco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SOS_Buscas.Models.Desaparecido", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataDesaparecimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoraDesaparecimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Desaparecido");
                });

            modelBuilder.Entity("SOS_Buscas.Models.Descricao", b =>
                {
                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<string>("CorCabelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorPele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DesaparecidoID")
                        .HasColumnType("int");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roupa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TamanhoCabelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tatuagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("DesaparecidoID");

                    b.ToTable("Descricao");
                });

            modelBuilder.Entity("SOS_Buscas.Models.Endereco", b =>
                {
                    b.Property<int>("CEP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CEP"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DesaparecidoID")
                        .HasColumnType("int");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CEP");

                    b.HasIndex("DesaparecidoID");

                    b.HasIndex("UserID");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("SOS_Buscas.Models.Familiar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DesaparecidoID")
                        .HasColumnType("int");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parentesco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DesaparecidoID");

                    b.ToTable("Familiar");
                });

            modelBuilder.Entity("SOS_Buscas.Models.HistoricoAvistamento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataDesaparecimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("DesaparecidoID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DesaparecidoID");

                    b.HasIndex("UserID");

                    b.ToTable("HistoricoAvistamentos");
                });

            modelBuilder.Entity("SOS_Buscas.Models.LocalAvistamento", b =>
                {
                    b.Property<int>("AvistamentoID")
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PontoReferencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AvistamentoID");

                    b.ToTable("LocalAvistamentos");
                });

            modelBuilder.Entity("SOS_Buscas.Models.Telefone", b =>
                {
                    b.Property<int>("Cod_Area")
                        .HasColumnType("int");

                    b.Property<int>("DesaparecidoID")
                        .HasColumnType("int");

                    b.Property<int>("FamiliarID")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasIndex("DesaparecidoID");

                    b.HasIndex("FamiliarID");

                    b.HasIndex("UserID");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("SOS_Buscas.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CPF")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SOS_Buscas.Models.Desaparecido", b =>
                {
                    b.HasOne("SOS_Buscas.Models.User", "User")
                        .WithOne("Desaparecido")
                        .HasForeignKey("SOS_Buscas.Models.Desaparecido", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOS_Buscas.Models.Descricao", b =>
                {
                    b.HasOne("SOS_Buscas.Models.Desaparecido", "Desaparecido")
                        .WithMany()
                        .HasForeignKey("DesaparecidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desaparecido");
                });

            modelBuilder.Entity("SOS_Buscas.Models.Endereco", b =>
                {
                    b.HasOne("SOS_Buscas.Models.Desaparecido", "Desaparecido")
                        .WithMany()
                        .HasForeignKey("DesaparecidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOS_Buscas.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desaparecido");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOS_Buscas.Models.Familiar", b =>
                {
                    b.HasOne("SOS_Buscas.Models.Desaparecido", "Desaparecido")
                        .WithMany()
                        .HasForeignKey("DesaparecidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desaparecido");
                });

            modelBuilder.Entity("SOS_Buscas.Models.HistoricoAvistamento", b =>
                {
                    b.HasOne("SOS_Buscas.Models.Desaparecido", "Desaparecido")
                        .WithMany()
                        .HasForeignKey("DesaparecidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOS_Buscas.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desaparecido");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOS_Buscas.Models.LocalAvistamento", b =>
                {
                    b.HasOne("SOS_Buscas.Models.HistoricoAvistamento", "HistoricoAvistamento")
                        .WithMany()
                        .HasForeignKey("AvistamentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoricoAvistamento");
                });

            modelBuilder.Entity("SOS_Buscas.Models.Telefone", b =>
                {
                    b.HasOne("SOS_Buscas.Models.Desaparecido", "Desaparecido")
                        .WithMany()
                        .HasForeignKey("DesaparecidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOS_Buscas.Models.Familiar", "Familiar")
                        .WithMany()
                        .HasForeignKey("FamiliarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOS_Buscas.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desaparecido");

                    b.Navigation("Familiar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOS_Buscas.Models.User", b =>
                {
                    b.Navigation("Desaparecido")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
