// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOS_Buscas_V2.Data;

#nullable disable

namespace SOS_Buscas_V2.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20230616174319_TESTE")]
    partial class TESTE
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SOS_Buscas_V2.Models.DesaparecidoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Altura")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Avistamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaminhoImagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContatoFamiliar")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContatoFamiliar2")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CorPele")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("DataHoraDesaparecimento")
                        .HasColumnType("DateTime");

                    b.Property<string>("Doencas")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EstiloCorCabelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GrauParentesco2")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Medicacoes")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("NomeFamiliar")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NomeFamiliar2")
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Tatuagem")
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Transtornos")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vestimenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmailUsuario");

                    b.ToTable("Desaparecidos");
                });

            modelBuilder.Entity("SOS_Buscas_V2.Models.UsuarioModel", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("DateTime");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("Email");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SOS_Buscas_V2.Models.DesaparecidoModel", b =>
                {
                    b.HasOne("SOS_Buscas_V2.Models.UsuarioModel", "Email")
                        .WithMany()
                        .HasForeignKey("EmailUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });
#pragma warning restore 612, 618
        }
    }
}
